/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database.DatabaseConnection;

/**
 *
 * @author 96654
 */
public class CashierManagerInterface extends javax.swing.JFrame {

    /**
     * Creates new form CashierManagerInterface
     */
    public CashierManagerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCMinterface = new javax.swing.JPanel();
        lblCMinterface = new javax.swing.JLabel();
        lblUname = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblUtype = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        btnlog = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboUtype = new javax.swing.JComboBox<>();
        jPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCMinterface.setBackground(new java.awt.Color(0, 153, 204));

        lblCMinterface.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblCMinterface.setText("Apple I Mission");

        javax.swing.GroupLayout jPanelCMinterfaceLayout = new javax.swing.GroupLayout(jPanelCMinterface);
        jPanelCMinterface.setLayout(jPanelCMinterfaceLayout);
        jPanelCMinterfaceLayout.setHorizontalGroup(
            jPanelCMinterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCMinterfaceLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(lblCMinterface, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );
        jPanelCMinterfaceLayout.setVerticalGroup(
            jPanelCMinterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCMinterfaceLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCMinterface)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCMinterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 100));

        lblUname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUname.setText("User Name");
        getContentPane().add(lblUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 20));

        lblPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPass.setText("Password");
        getContentPane().add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        lblUtype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUtype.setText("User Type");
        getContentPane().add(lblUtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 432, -1, -1));

        txtUname.setBackground(new java.awt.Color(204, 204, 204));
        txtUname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 194, -1));

        btnlog.setBackground(new java.awt.Color(0, 0, 204));
        btnlog.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlog.setForeground(new java.awt.Color(255, 255, 255));
        btnlog.setText("Login");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 513, 80, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 204));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 513, -1, -1));

        comboUtype.setBackground(new java.awt.Color(204, 204, 204));
        comboUtype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboUtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cashier", "manager" }));
        comboUtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUtypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboUtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 194, -1));

        jPass.setBackground(new java.awt.Color(204, 204, 204));
        jPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 194, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6310507 (1) (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 440, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 91, 103));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 460, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
        DatabaseConnection db= new DatabaseConnection();
        String userName=txtUname.getText();
        String password=jPass.getText();
        String userType=comboUtype.getSelectedItem().toString();
        db.login(userName,password,userType);
     
    }//GEN-LAST:event_btnlogActionPerformed

    private void comboUtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUtypeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtUname.setText("");
        jPass.setText("");
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnlog;
    private javax.swing.JComboBox<String> comboUtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCMinterface;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JLabel lblCMinterface;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblUtype;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
