/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import ControllingMethods.ManagerController;

/**
 *
 * @author 96654
 */
public class CreateNew extends javax.swing.JFrame {

    /**
     * Creates new form CreateNew
     */
    public CreateNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUname = new javax.swing.JLabel();
        lblUpassword = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblUtype = new javax.swing.JLabel();
        btnCreateNewCan = new javax.swing.JButton();
        txtUname = new javax.swing.JTextField();
        cmbUtype = new javax.swing.JComboBox<>();
        jPanelCreate = new javax.swing.JPanel();
        lblCreateNew = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JPasswordField();
        jConfPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUname.setText("User Name");

        lblUpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUpassword.setText("Password");

        lblConfirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblConfirm.setText("Confirm Password");

        btnCreate.setBackground(new java.awt.Color(204, 204, 255));
        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 51, 204));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblUtype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUtype.setText("User Type");

        btnCreateNewCan.setBackground(new java.awt.Color(204, 204, 255));
        btnCreateNewCan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateNewCan.setForeground(new java.awt.Color(0, 51, 204));
        btnCreateNewCan.setText("Cancel");
        btnCreateNewCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewCanActionPerformed(evt);
            }
        });

        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        cmbUtype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbUtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cashier", "manager" }));

        jPanelCreate.setBackground(new java.awt.Color(153, 153, 255));

        lblCreateNew.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreateNew.setForeground(new java.awt.Color(0, 0, 204));
        lblCreateNew.setText("Create New Account");

        javax.swing.GroupLayout jPanelCreateLayout = new javax.swing.GroupLayout(jPanelCreate);
        jPanelCreate.setLayout(jPanelCreateLayout);
        jPanelCreateLayout.setHorizontalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCreateNew, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCreateLayout.setVerticalGroup(
            jPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateNew)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPassword1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jConfPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpassword)
                    .addComponent(lblUname)
                    .addComponent(lblConfirm)
                    .addComponent(lblUtype))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateNewCan))
                    .addComponent(cmbUtype, 0, 204, Short.MAX_VALUE)
                    .addComponent(txtUname, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPassword1)
                    .addComponent(jConfPassword))
                .addContainerGap(195, Short.MAX_VALUE))
            .addComponent(jPanelCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUname)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpassword)
                    .addComponent(jPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirm)
                    .addComponent(jConfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtype)
                    .addComponent(cmbUtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCreateNewCan))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
         String username=txtUname.getText();
         String password=jPassword1.getText();
         String confirmpassword=jConfPassword.getText();
         String userType=cmbUtype.getSelectedItem().toString();
        ManagerController m1=new ManagerController();
        m1.createNewAccount(username,password,userType);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void btnCreateNewCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewCanActionPerformed
        // TODO add your handling code here:
        txtUname.setText("");
        jPassword1.setText("");
        jConfPassword.setText("");
        
    }//GEN-LAST:event_btnCreateNewCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateNewCan;
    private javax.swing.JComboBox<String> cmbUtype;
    private javax.swing.JPasswordField jConfPassword;
    private javax.swing.JPanel jPanelCreate;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblCreateNew;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblUpassword;
    private javax.swing.JLabel lblUtype;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
